---
driver:
  name: vagrant
  synced_folders: 
  - ["~/shuttle","/home/vagrant/shuttle"]
  - ["~/work/java_eclipse","/home/vagrant/java_eclipse"]

provisioner:
  name: chef_zero

platforms:
- name: box-cutter-VAGRANTSLASH-ubuntu1404-desktop
  driver_config:
    box: box-cutter-VAGRANTSLASH-ubuntu1404-desktop
    box_url: ~/Vagrant\ boxes/box-cutter-VAGRANTSLASH-ubuntu1404-desktop
    network:
    - ["private_network", {ip: "192.168.33.33"}]

suites:
  - name: dfdevm_java_eclipse
    run_list:
      - recipe[dfdevm_java_eclipse::default]
    attributes:
