---
driver:
  name: vagrant
  synced_folders: 
  - ["~/shuttle","/opt/shuttle"]
  - ["~/work/polymer","/home/vagrant/polymer"]

provisioner:
  name: chef_zero

platforms:
- name: boxcutter-VAGRANTSLASH-ubuntu1404-desktop
  driver_config:
    box: boxcutter-VAGRANTSLASH-ubuntu1404-desktop
    box_url: ~/Vagrant\ Boxes/boxcutter-VAGRANTSLASH-ubuntu1404-desktop

suites:
  - name: dfdevm_java_eclipse
    run_list:
      - recipe[dfdevm_java_eclipse::default]
    attributes:
