name             'dfdevm_java_eclipse'
maintainer       'Pete Carapetyan'
maintainer_email 'pete@datafundamentals.com'
license          'all_rights'
description      'Installs/Configures dfdevm_java_eclipse'
long_description 'Installs/Configures eclipse ee with java and maven'
version          '0.1.0'

depends 'df_java'
depends 'df_maven'
depends 'df_eclipse_ee'