Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "box-cutter-VAGRANTSLASH-ubuntu1404-desktop"
  c.vm.box_url = "~/Vagrant\ boxes/box-cutter-VAGRANTSLASH-ubuntu1404-desktop"
  c.vm.hostname = "dfdevm-java-eclipse-box-cutter-VAGRANTSLASH-ubuntu1404-desktop"
  c.vm.network(:private_network, {:ip=>"192.168.33.33"})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/Users/petecarapetyan/shuttle", "/home/vagrant/shuttle", nil
  c.vm.synced_folder "/Users/petecarapetyan/work/java_eclipse", "/home/vagrant/java_eclipse", nil
  c.vm.provider :virtualbox do |p|
  end
end
