Vagrant.configure("2") do |c|
  c.vm.box = "boxcutter-VAGRANTSLASH-ubuntu1404-desktop"
  c.vm.box_url = "~/Vagrant\ Boxes/boxcutter-VAGRANTSLASH-ubuntu1404-desktop"
  c.vm.hostname = "default-boxcutter-VAGRANTSLASH-ubuntu1404-desktop.vagrantup.com"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
  end
end
